mesh_folders:
  - "./assets/mpz14"
cache_dir: "./eigen_cache/schrodinger"
num_eigenfunctions: 50
num_workers: 8
min_file_size_mb: 0
max_file_size_mb: 7

operator:
  _target_: neural_laplacian.configs.OperatorConfig
  type: schrodinger
  potential_type: curvature
  potential_strength: 5.0