name: neural-laplacian
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python==3.10
  - pytorch
  - torchaudio
  - torchvision
  - pytorch-cuda=12.4
  - pyg
  - pytorch-scatter
  - pytorch-sparse
  - pytorch-cluster
  - scipy
  - jupyterlab
  - pandas
  - pip
  - meshio
  - trimesh
  - lightning
  - cython
  - eigen
  - cmake
  - lz4
  - boost
  - pybind11
  - pytest
  - pip:
    - numpy
    - wandb
    - gitpython
    - opencv-python
    - joblib
    - libigl
    - hydra-core
    - hydra-zen
    - imageio
    - open3d
    - pygltflib
    - rich
    - inflection
    - plyfile
    - polyscope
    - robust-laplacian
    - pymeshlab
    - deltaconv
    - pygeodesic
    - siren-pytorch
    - lightly
    - triangle
    - bpy
    - pyglet
    - pyfmaps
    - seaborn
    - scikit-learn
    - noise
